language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew uninstall xctool && brew install xctool

script:
    - xctool -workspace AeroGear-iOS.xcworkspace -scheme AeroGear-iOSTests -sdk iphonesimulator -configuration Release test

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master

