language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew uninstall xctool && brew install xctool
    - cd AeroGear-iOS

script:
    - xctool test

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master

